blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Website
    url: https://whatsappauthbot.com
    about: You will be redirected to the WhatsApp Authenticator website!
  - name: ğŸ‡ºğŸ‡¸ Invite Bot | ğŸ‡§ğŸ‡· Convidar Bot
    url: https://discord.com/oauth2/authorize?client_id=854509145021874186&permissions=275146722308&scope=bot%20applications.commands
    about: ğŸ‡ºğŸ‡¸ Add the WhatsApp Authenticator to your server! | ğŸ‡§ğŸ‡· Convide o WhatsApp Authenticator para o seu servidor
  - name: ğŸ‡ºğŸ‡¸ Documentation
    url: https://docs.whatsappauthbot.com/
    about: You will be redirected to Documentation!
  - name: ğŸ‡§ğŸ‡· DocumentaÃ§Ã£o (PortuguÃªs)
    url: https://docs.whatsappauthbot.com/v/br/
    about: VocÃª serÃ¡ redirecionado para a documentaÃ§Ã£o!
  - name: ğŸ‡ºğŸ‡¸ Terms Of Use
    url: https://docs.whatsappauthbot.com/terms
    about: Terms of Use of WhatsApp Authenticator!
  - name: ğŸ‡§ğŸ‡· Termos de Uso (PortuguÃªs)
    url: https://docs.whatsappauthbot.com/v/br/termos
    about: Termos de Uso do WhatsApp Authenticator!
  - name: ğŸ‡ºğŸ‡¸ | ğŸ‡§ğŸ‡· Server | Community & Support
    url: https://discord.gg/hnq5ptdmZ2
    about: ğŸ‡ºğŸ‡¸ Server Invite! | ğŸ‡§ğŸ‡· Convite para o servidor!
  - name: I'm banned from the support server
    url: https://dyno.gg/form/14ad9883
    about: Click to be redirected to the unban request form, if the form is not displayed to you, it is considered that you have not been banned from the WhatsApp Authenticator support server or that you have logged into an account other than the banned one.
